# Generated by Django 2.0.4 on 2018-05-03 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_adddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发帖时间')),
                ('blog_title', models.CharField(default='********', max_length=20)),
                ('blog_label', models.IntegerField(choices=[(0, '失物招领'), (1, '卖室友'), (2, '找朋友'), (3, '广告'), (4, '发心情')], default=1)),
                ('blog_text', models.TextField()),
                ('blog_image1', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image2', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image3', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image4', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image5', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image6', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image7', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image8', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_image9', models.ImageField(blank=True, default='', upload_to='images')),
                ('blog_iscomment', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('blog_adddate',),
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_nickname', models.CharField(default='例如   XXX', max_length=20, verbose_name='昵称')),
                ('user_password', models.CharField(default='123456', max_length=16, verbose_name='密码')),
                ('user_image', models.ImageField(upload_to='', verbose_name='头像')),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.AddField(
            model_name='fan',
            name='fan',
            field=models.ForeignKey(on_delete=True, related_name='friend4', to='blog.Student'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog',
            field=models.ForeignKey(on_delete=True, related_name='friend1', to='blog.Student'),
        ),
        migrations.AddField(
            model_name='agree',
            name='agree',
            field=models.ForeignKey(on_delete=True, related_name='friend3', to='blog.Blog'),
        ),
    ]
