# Generated by Django 2.0.4 on 2018-05-03 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='评论区')),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('comment', models.ForeignKey(on_delete=True, related_name='friend2', to='blog.Blog')),
            ],
            options={
                'ordering': ('comment_time',),
            },
        ),
    ]
